sudo: true

matrix:
  include:
    - os: linux
      env: CXX=g++-5
      compiler: clang
      language: java
      jdk: oraclejdk7
    - os: osx
      compiler: clang
      language: java
      osx_image: xcode8.1

script:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then cd runtime-testsuite; ../.travis/run-tests-macos.sh; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then cd runtime-testsuite; ../.travis/run-tests-linux.sh; fi

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then ./.travis/before-install-macos.sh; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then ./.travis/before-install-linux.sh; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - g++-5
      - uuid-dev
      - clang-3.7
