sudo: true

language: java

compiler: clang

matrix:
  include:
    - os: linux
      jdk: oraclejdk7
      env: 
        - TARGET=cpp
        - CXX=g++-5
    - os: osx
      compiler: clang
      osx_image: xcode8.1
      env: TARGET=cpp
    - os: linux
      jdk: oraclejdk7
      env: TARGET=java
    - os: linux
      jdk: oraclejdk8
      env: TARGET=java
    - os: linux
      jdk: oraclejdk7
      env: TARGET=csharp
    - os: linux
      jdk: oraclejdk7
      env: TARGET=python2
    - os: linux
      jdk: oraclejdk7
      env: TARGET=python3
    - os: linux
      jdk: oraclejdk7
      env: TARGET=javascript
    - os: linux
      jdk: oraclejdk7
      env: TARGET=go
    - os: osx
      compiler: clang
      osx_image: xcode8.1
      env: TARGET=swift

before_install:
  - ./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh

script:
  - cd runtime-testsuite
  - ../.travis/run-tests-$TARGET.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - g++-5
      - uuid-dev
      - clang-3.7
