sudo: true

language: java

env:
 - TARGET=java
 - TARGET=csharp
 - TARGET=python2
 - TARGET=python3
 - TARGET=javascript
 - TARGET=cpp
 - TARGET=go
 - TARGET=swift
 
matrix:
  include:
    - os: linux
      env: CXX=g++-5
      compiler: clang
      jdk: oraclejdk7
    - os: osx
      compiler: clang
      osx_image: xcode8.1
  exclude:
    - os: linux
      env: TARGET=swift
    - os: osx
      env: TARGET=java
    - os: osx
      env: TARGET=csharp
    - os: osx
      env: TARGET=python2
    - os: osx
      env: TARGET=python3
    - os: osx
      env: TARGET=javascript
    - os: osx
      env: TARGET=cpp
    - os: osx
      env: TARGET=go
      
before_install:
  - ./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh
  - fi

script:
  - cd runtime-testsuite
  - ../.travis/run-tests-$TARGET.sh
  - fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - g++-5
      - uuid-dev
      - clang-3.7
